version: "3.9"
services:
  frontend:
    container_name: flask_frontend_c
    image: flask_frontend_i
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: npm run dev

  backend:
    container_name: flask-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/delta-db
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    command: ./wait-for-db.sh db flask run --host=0.0.0.0 --reload  # Hot reload enabled

  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delta-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

